### ISSUE TITLE
Commands are Pro-Tracker, not Scream-Tracker style

### ISSUE THREAD

**Issue by reduz** [hukkax/Propulse#3]
If you are making an impulse-tracker style tracker, the commands should also be scream-tracker style, not protracker. It kind of beats the purpose of using this application..

**Comment by hukkax** [comment]
IT-style commands used to be an option but my reasons for removing it were:

1. It made the code too complicated.
2. It didn't make sense with a number of effects because of the way the parameters differ between IT and PT modules, so you ended up with something that looked like IT commands but with the parameters working differently to IT anyway. Keep in mind we're still working within ProTracker limitations here.
